services:
  asudir-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asudir-proxy
    ports:
      - "${APP_PORT}:3000"
    environment:
      STRAPI_URL: "${STRAPI_URL}"
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules